import * as fs from "node:fs";
import * as path from "node:path";

import { blueBright, green, yellowBright } from "chalk";

import { build, EBuildTarget } from "#/build/build";
import { transpileChecks } from "#/checks/build_checks";
import { default as config } from "#/config.json";
import { TARGET_GAME_DATA_CHECKS_MCP_DIR, TARGET_GAME_DATA_MCP_EXTENSION_DIR } from "#/globals/paths";
import { NodeLogger } from "#/utils/logging";
import { TimeTracker } from "#/utils/timing";

import { mcpConfig } from "@/engine/checks/mcp/McpConfig";

const log: NodeLogger = NodeLogger.forFile(__filename);

/**
 * Extension files the loader looks for, each loading a module the checks transpile emits.
 */
export const MCP_EXTENSION_FILES: Array<{ file: string; module: string; emitted: string }> = [
  { file: "main.script", module: "checks.mcp.extension", emitted: "extension.script" },
  { file: "check.script", module: "checks.mcp.extension_check", emitted: "extension_check.script" },
];

export interface IBuildMcpParameters {
  scripts?: boolean;
  verbose?: boolean;
}

/**
 * Transpile the game MCP endpoint into gamedata and write the extension that starts it.
 *
 * The endpoint stays inert until the game is launched with the arming flag, and no release build contains it:
 * running this command is the only way it reaches gamedata.
 */
export async function buildMcp(parameters: IBuildMcpParameters = {}): Promise<void> {
  if (parameters.scripts) {
    await build({
      include: [EBuildTarget.SCRIPTS],
      exclude: [],
      filter: [],
      assetOverrides: true,
      luaLogs: true,
      language: config.locale,
      verbose: parameters.verbose,
    });
  }

  NodeLogger.IS_VERBOSE = Boolean(parameters.verbose);

  log.info(blueBright("Build game MCP endpoint"));

  const timeTracker: TimeTracker = new TimeTracker().start();

  transpileChecks();
  timeTracker.addMark("MCP_TRANSPILED");

  writeMcpExtension();
  timeTracker.addMark("MCP_EXTENSION");

  log.info("Game MCP endpoint built in", timeTracker.end().getDuration() / 1000, "sec");
  log.info("Arm it by launching the engine with", yellowBright(mcpConfig.LAUNCH_FLAG));
}

/**
 * Write the extension files, each loading a transpiled endpoint module.
 */
export function writeMcpExtension(): void {
  fs.mkdirSync(TARGET_GAME_DATA_MCP_EXTENSION_DIR, { recursive: true });

  for (const entry of MCP_EXTENSION_FILES) {
    const emittedPath: string = path.resolve(TARGET_GAME_DATA_CHECKS_MCP_DIR, entry.emitted);

    // A file loading a module that does not exist would only fail once the game starts armed.
    if (!fs.existsSync(emittedPath)) {
      throw new Error(`Expected transpiled endpoint module at '${emittedPath}' for '${entry.module}'.`);
    }

    fs.writeFileSync(
      path.resolve(TARGET_GAME_DATA_MCP_EXTENSION_DIR, entry.file),
      `-- Generated by 'xrf mcp build'. Do not edit.\nreturn require("${entry.module}")\n`,
      "utf8"
    );
  }

  log.info("Emitted extension:", green(TARGET_GAME_DATA_MCP_EXTENSION_DIR));
}
